/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
  id("com.hantasmate.iris.plugin.library")
//  `java-library`
//  `kotlin-dsl`
}

//repositories {
//  // Use the plugin portal to apply community plugins in convention plugins.
//  gradlePluginPortal()
//  mavenCentral()
//}

dependencies {
  api(project(":list"))
}
