/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("iris.java-library-conventions")
}

//dependencies {
//    implementation(libs.assertj.core)
//}
