/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
  id("com.hantasmate.iris.plugin.base")
}

irisBase {
  name.set("123")
  version.set(321)
}

println(irisBase.name.get())
println(irisBase.version.get())

dependencies {
//  implementation(myex.libs.findLibrary("assertj-core").get())
}
