import org.gradle.kotlin.dsl.`java-library`

/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Apply the common convention plugin for shared build configuration between library and application projects.
    id("com.hantasmate.iris.gradle.plugin.common")

    // Apply the java-library plugin for API and implementation separation.
    `java-library`
}
